-- MySQL Script generated by MySQL Workbench
-- Thu Dec 24 23:57:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mms` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mms
-- -----------------------------------------------------
USE `mms` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`ROLES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`USERS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `BIRTHDAY` DATE NULL,
  `EMAIL` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(60) NULL,
  `ROLE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`, `ROLE_ID`),
  INDEX `fk_USERS_ROLES1_idx` (`ROLE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_ROLES1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `mms`.`ROLES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUSTOMERS_ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`CUSTOMERS_ADDRESSES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `COUNTRY` VARCHAR(45) NULL,
  `CITY` VARCHAR(45) NULL,
  `POSTCODE` VARCHAR(45) NULL,
  `STREET` VARCHAR(45) NULL,
  `HOUSE` VARCHAR(45) NULL,
  `APARTMENT` VARCHAR(45) NULL,
  `USER_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`, `USER_ID`),
  INDEX `fk_CUSTOMERS_ADDRESSES_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMERS_ADDRESSES_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mms`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mms`.`PAYMENT_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`PAYMENT_METHODS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`PAYMENT_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`PAYMENT_STATUSES` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`DELIVERY_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`DELIVERY_METHODS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`DELIVERY_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`DELIVERY_STATUSES` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`ORDERS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `CUSTOMER_ADDRESS_ID` BIGINT NULL,
    `PAYMENT_METHOD_ID` BIGINT NULL,
    `PAYMENT_STATUS_ID` BIGINT NULL,
    `DELIVERY_METHOD_ID` BIGINT NULL,
    `DELIVERY_STATUS_ID` BIGINT NULL,
    PRIMARY KEY (`ID`, `USER_ID`),
    INDEX `fk_ORDERS_USER1_idx` (`USER_ID` ASC) VISIBLE,
    INDEX `fk_ORDERS_CUSTOMERS_ADDRESSES1_idx` (`CUSTOMER_ADDRESS_ID` ASC) VISIBLE,
    INDEX `fk_ORDERS_PAYMENT_METHOD1_idx` (`PAYMENT_METHOD_ID` ASC) VISIBLE,
    INDEX `fk_ORDERS_PAYMENT_STATUS1_idx` (`PAYMENT_STATUS_ID` ASC) VISIBLE,
    INDEX `fk_ORDERS_DELIVERY_METHOD1_idx` (`DELIVERY_METHOD_ID` ASC) VISIBLE,
    INDEX `fk_ORDERS_DELIVERY_STATUS1_idx` (`DELIVERY_STATUS_ID` ASC) VISIBLE,
    CONSTRAINT `fk_ORDERS_USER1`
        FOREIGN KEY (`USER_ID`)
            REFERENCES `mms`.`USERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDERS_CUSTOMERS_ADDRESSES1`
        FOREIGN KEY (`CUSTOMER_ADDRESS_ID`)
            REFERENCES `mms`.`CUSTOMERS_ADDRESSES` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDERS_PAYMENT_METHOD1`
        FOREIGN KEY (`PAYMENT_METHOD_ID`)
            REFERENCES `mms`.`PAYMENT_METHODS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDERS_PAYMENT_STATUS1`
        FOREIGN KEY (`PAYMENT_STATUS_ID`)
            REFERENCES `mms`.`PAYMENT_STATUSES` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDERS_DELIVERY_METHOD1`
        FOREIGN KEY (`DELIVERY_METHOD_ID`)
            REFERENCES `mms`.`DELIVERY_METHODS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_ORDERS_DELIVERY_STATUS1`
        FOREIGN KEY (`DELIVERY_STATUS_ID`)
            REFERENCES `mms`.`DELIVERY_STATUSES` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ORDER_PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`ORDER_PRODUCTS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NULL,
    `PRICE` DOUBLE NULL,
    `WEIGHT` DOUBLE NULL,
    `VOLUME` DOUBLE NULL,
    `QUANTITY` INT NULL,
    `ORDER_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NULL,
    PRIMARY KEY (`ID`, `ORDER_ID`),
    INDEX `fk_PRODUCTS_copy1_ORDERS1_idx` (`ORDER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_PRODUCTS_copy1_ORDERS1`
        FOREIGN KEY (`ORDER_ID`)
            REFERENCES `mms`.`ORDERS` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
    ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`CATEGORIES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`PRODUCTS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `PRICE` DOUBLE NULL,
  `WEIGHT` DOUBLE NULL,
  `VOLUME` DOUBLE NULL,
  `STOCK` INT NULL,
  `CATEGORY_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`, `CATEGORY_ID`),
  INDEX `fk_PRODUCTS_CATEGORIES1_idx` (`CATEGORY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTS_CATEGORIES1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `mms`.`CATEGORIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mms`.`CARTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`CARTS`(
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NULL,
    `QUANTITY` INT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_CARTS_PRODUCTS1_idx` (`PRODUCT_ID` ASC) VISIBLE,
    INDEX `fk_CARTS_USERS1_idx` (`USER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_CARTS_PRODUCTS1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mms`.`PRODUCTS` (`ID`)
    ON DELETE NO ACTION
       ON UPDATE NO ACTION,
              CONSTRAINT `fk_CARTS_USERS1`
              FOREIGN KEY (`USER_ID`)
              REFERENCES `mms`.`USERS` (`ID`)
          ON DELETE NO ACTION
             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPERTIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`PROPERTIES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `TYPE` VARCHAR(45) NULL,
  `CATEGORY_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`, `CATEGORY_ID`),
  INDEX `fk_PROPERTIES_CATEGORIES1_idx` (`CATEGORY_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROPERTIES_CATEGORIES1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `mms`.`CATEGORIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROPERTY_VALUES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`PROPERTY_VALUES` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `VALUE` VARCHAR(45) NULL,
  `PROPERTY_ID` BIGINT NOT NULL,
  `PRODUCT_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`, `PROPERTY_ID`, `PRODUCT_ID`),
  INDEX `fk_PROPERTY_VALUES_PROPERTIES1_idx` (`PROPERTY_ID` ASC) VISIBLE,
  INDEX `fk_PROPERTY_VALUES_PRODUCTS1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROPERTY_VALUES_PROPERTIES1`
    FOREIGN KEY (`PROPERTY_ID`)
    REFERENCES `mms`.`PROPERTIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROPERTY_VALUES_PRODUCTS1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `mms`.`PRODUCTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER_PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mms`.`ORDER_PRODUCTS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `PRICE` DOUBLE NULL,
  `WEIGHT` DOUBLE NULL,
  `VOLUME` DOUBLE NULL,
  `QUANTITY` INT NULL,
  `ORDER_ID` BIGINT NOT NULL,
  `PRODUCT_ID` BIGINT NULL,
  PRIMARY KEY (`ID`, `ORDER_ID`),
  INDEX `fk_PRODUCTS_copy1_ORDERS1_idx` (`ORDER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTS_copy1_ORDERS1`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mms`.`ORDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
--
--
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
